
* 生成compile_commands.json                                      :tool:cmake:
在CMakeLists.txt中添加 set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
在命令行中添加-DCMAKE_EXPORT_COMPILE_COMMANDS=on
iar工具生成compile_commands.json: iarbuild.exe tumia.ewp -jsondb Debug -output compile_commands.json

* git                                                              :tool:git:
1. 解决二进制文件合并冲突问题
   git checkout [--theirs/--ours] -- path/to/binaryfile
   git add path/to/binaryfile
   即ours是当前分支的，theirs是被合并的分支的

* split                                                          :tool:shell:split:
1. split -b 50m bdsc.log -d bdsc_ 分割文件

* beyondcompare                                          :tool:beyondcompare:
破解:
1.删去下面目录中的一切文件：
/home/xxx/.config/bcompare
2.从头破解
$cd /usr/lib/beyondcompare/
$sudo sed -i "s/keexjEP3t4Mue23hrnuPtY4TdcsqNiJL-5174TsUdLmJSIXKfG2NGPwBL6vnRPddT7tH29qpkneX63DO9ECSPE9rzY1zhThHERg8lHM9IBFT+rVuiY823aQJuqzxCKIE1bcDqM4wgW01FH6oCBP1G4ub01xmb4BGSUG6ZrjxWHJyNLyIlGvOhoY2HAYzEtzYGwxFZn2JZ66o4RONkXjX0DF9EzsdUef3UAS+JQ+fCYReLawdjEe6tXCv88GKaaPKWxCeaUL9PejICQgRQOLGOZtZQkLgAelrOtehxz5ANOOqCaJgy2mJLQVLM5SJ9Dli909c5ybvEhVmIC0dc9dWH+/N9KmiLVlKMU7RJqnE+WXEEPI1SgglmfmLc1yVH7dqBb9ehOoKG9UE+HAE1YvH1XX2XVGeEqYUY-Tsk7YBTz0WpSpoYyPgx6Iki5KLtQ5G-aKP9eysnkuOAkrvHU8bLbGtZteGwJarev03PhfCioJL4OSqsmQGEvDbHFEbNl1qJtdwEriR+VNZts9vNNLk7UGfeNwIiqpxjk4Mn09nmSd8FhM4ifvcaIbNCRoMPGl6KU12iseSe+w+1kFsLhX+OhQM8WXcWV10cGqBzQE9OqOLUcg9n0krrR3KrohstS9smTwEx9olyLYppvC0p5i7dAx2deWvM1ZxKNs0BvcXGukR+/g" BCompare
3.此时BCompare文件已被破解，翻开软件会提示“Trial Mode Error！”表明成功，输入下面TEAM ZWT生成的密钥即可注册成功
--- BEGIN LICENSE KEY ---
GXN1eh9FbDiX1ACdd7XKMV7hL7x0ClBJLUJ-zFfKofjaj2yxE53xauIfkqZ8FoLpcZ0Ux6McTyNmODDSvSIHLYhg1QkTxjCeSCk6ARz0ABJcnUmd3dZYJNWFyJun14rmGByRnVPL49QH+Rs0kjRGKCB-cb8IT4Gf0Ue9WMQ1A6t31MO9jmjoYUeoUmbeAQSofvuK8GN1rLRv7WXfUJ0uyvYlGLqzq1ZoJAJDyo0Kdr4ThF-IXcv2cxVyWVW1SaMq8GFosDEGThnY7C-SgNXW30jqAOgiRjKKRX9RuNeDMFqgP2cuf0NMvyMrMScnM1ZyiAaJJtzbxqN5hZOMClUTE+++
--- END LICENSE KEY -----

* emacs                                                    :tool:emacs:elisp:
1. elisp用户手册
   https://www.gnu.org/software/emacs/manual/html_node/eintr/index.html
   or C-h i m elisp在emacs内阅读
2. undo-tree
   1. 修复treemacs窗口突变问题
      open undo-tree.el (in my case located at ~/.emacs.d/elpa/27.1/develop/undo-tree-0.8.2/undo-tree.el) and edit the line that says (balance-windows). Replace it with (balance-windows (window-parent win))

* semgrep                                                      :tool:semgrep:
1. token
   Login enables additional proprietary Semgrep Registry rules and running custom policies from Semgrep Cloud Platform.
Opening login at: https://semgrep.dev/login?cli-token=3b03d74a-655f-4066-8f57-5d7eb5249f94&docker=False&gha=False

Once you've logged in, return here and you'll be ready to start using new Semgrep rules.
Opening in existing browser session.
Saved login token

	6e8862ce2f69eba149b45e187a75d807f2b659b6a8d57328df072a7bdc880d67

in /home/liweigao/.semgrep/settings.yml.
Note: You can always generate more tokens at https://semgrep.dev/orgs/-/settings/tokens

* github                                                        :tool:github:
1. unable to access,http code 503
   unable to access 'https://github.com/melpa/melpa.git/': Received HTTP code 503 from proxy after CONNECT
   解决办法：git config --global --unset http.proxy

* rust                                                            :tool:rust:
1. rust安装
   https://blog.csdn.net/qq_35241329/article/details/135527371
   curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh
   . "$HOME/.cargo/env"


